---
- hosts: all
  become: yes
  become_user: root
  tasks:

    - name: Enable software collection for httpd24
      yum:
        name:
          - centos-release-scl-rh
        state: present

    - name: Install build tooling for Earthdata Drive modules
      yum:
        name:
          - httpd24-httpd-devel
          - httpd24-mod_ssl
          - openssl-devel
          - sqlite-devel
        state: present

    - name: Checkout earthdata-drive
      git:
        repo: file:///vagrant/earthdata-drive/.git
        dest: /tmp/checkout
