---
- hosts: all
  become: yes
  become_user: root
  tasks:

    - name: Enable software collection for httpd24
      yum:
        name:
          - centos-release-scl-rh
        state: present

    - name: "Install Web server packages"
      package:
        name:
          - "httpd24-httpd"
          - "httpd24-mod_ssl"
          - "apr-util-sqlite"
          - "python27-mod_wsgi"
          - "python27-python-virtualenv"
          - "/vagrant/httpd24-mod_auth_urs-password-1.4.1_1_g4cdc300-1.el7.centos.x86_64.rpm"
        state: "present"

    - name: Install build tooling for Earthdata Drive modules
      yum:
        name:
          - git
          - httpd24-httpd-devel
          - openssl-devel
          - sqlite-devel
        state: present

    - name: "Enable web services"
      service:
        name: "httpd24-httpd"
        enabled: "yes"
        state: "started"

    - name: "Prepare web apps folder"
      file:
        path: "/web/testdrive.internal/apps"
        state: "directory"
        mode: "0775"
        group: "vagrant"
        owner: "vagrant"

- hosts: all
  tasks:
    - name: Checkout earthdata-drive
      git:
        repo: file:///vagrant/earthdata-drive/.git
        dest: /home/vagrant/earthdata-drive
        version: "v1.4.1_1_g4cdc300"
    - name: "Deploy files for drive app"
      synchronize:
        src: "/home/vagrant/earthdata-drive/password_module/drive_files/"
        dest: "/web/testdrive.internal/apps/drive/"
    - name: "Prepare virtualenv for drive app"
      command: "scl enable python27 -- virtualenv /web/testdrive.internal/apps/drive.venv"
      args:
        creates: "/web/testdrive.internal/apps/drive.venv/bin/activate"
    - name: "Install requirements in virtualenv for drive app"
      command: "scl enable python27 -- bash -c '. /web/testdrive.internal/apps/drive.venv/bin/activate && pip install -r /home/vagrant/earthdata-drive/password_module/requirements.txt'"
      args:
        creates: "/web/testdrive.internal/apps/drive.venv/lib/python2.7/site-packages/flask/__init__.py"
    - name: "Install 'requests' in virtualenv for drive app"
      command: "scl enable python27 -- bash -c '. /web/testdrive.internal/apps/drive.venv/bin/activate && pip install requests'"
      args:
        creates: "/web/testdrive.internal/apps/drive.venv/lib/python2.7/site-packages/requests/__init__.py"
    - name: "Install 'python_memcached' in virtualenv for drive app"
      command: "scl enable python27 -- bash -c '. /web/testdrive.internal/apps/drive.venv/bin/activate && pip install python_memcached'"
      args:
        creates: "/web/testdrive.internal/apps/drive.venv/lib/python2.7/site-packages/memcache.py"
