---
- hosts: all
  become: yes
  become_user: root
  tasks:

    - name: Enable software collection for httpd24
      yum:
        name:
          - centos-release-scl-rh
        state: present

    - name: "Install Web server packages"
      package:
        name:
          - "httpd24-httpd"
          - "httpd24-mod_ssl"
          - "apr-util-sqlite"
          - "python27-mod_wsgi"
          - "python27-python-virtualenv"
          - "/vagrant/httpd24-mod_auth_urs-password-{{ mod_auth_urs_password_version }}-{{ mod_auth_urs_password_release }}.el7.centos.x86_64.rpm"
        state: "present"

    - name: Install build tooling for Earthdata Drive modules
      yum:
        name:
          - git
          - httpd24-httpd-devel
          - openssl-devel
          - sqlite-devel
        state: present

    - name: "Deploy httpd configuration files (templates)"
      template:
        src: "/vagrant/httpdconf/{{ item }}.template"
        dest: "/opt/rh/httpd24/root/etc/httpd/conf.d/{{ item }}"
      with_items:
        - "99-drive.conf"

    - name: "Prepare web apps folder"
      file:
        path: "{{ drive_site_apps_folder }}"
        state: "directory"
        mode: "0775"
        group: "vagrant"
        owner: "vagrant"

- hosts: all
  tasks:
    - name: Checkout earthdata-drive
      git:
        repo: file:///vagrant/earthdata-drive/.git
        dest: /home/vagrant/earthdata-drive
        version: "v{{ mod_auth_urs_password_version }}"
    - name: "Deploy files for drive app"
      synchronize:
        src: "/home/vagrant/earthdata-drive/password_module/drive_files/"
        dest: "{{ drive_app_folder }}/"
    - name: "Prepare virtualenv for drive app"
      command: "scl enable python27 -- virtualenv {{ drive_app_venv }}"
      args:
        creates: "{{ drive_app_venv }}/bin/activate"
    - name: "Install requirements in virtualenv for drive app"
      command: "scl enable python27 -- bash -c '. {{ drive_app_venv }}/bin/activate && pip install -r /home/vagrant/earthdata-drive/password_module/requirements.txt'"
      args:
        creates: "{{ drive_app_venv }}/lib/python2.7/site-packages/flask/__init__.py"
    - name: "Install 'requests' in virtualenv for drive app"
      command: "scl enable python27 -- bash -c '. {{ drive_app_venv }}/bin/activate && pip install requests'"
      args:
        creates: "{{ drive_app_venv }}/lib/python2.7/site-packages/requests/__init__.py"
    - name: "Install 'python_memcached' in virtualenv for drive app"
      command: "scl enable python27 -- bash -c '. {{ drive_app_venv }}/bin/activate && pip install python_memcached'"
      args:
        creates: "{{ drive_app_venv }}/lib/python2.7/site-packages/memcache.py"

- hosts: all
  become: yes
  become_user: root
  tasks:

    - name: "Enable web services"
      service:
        name: "httpd24-httpd"
        enabled: "yes"
        state: "started"
